<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\Core\Render\Markup;

/**
 * @file
 * Giai Điệu customization module.
 */
/**
 * Implements hook_preprocess_HOOK().
 */
function custom_preprocess_html(&$variables) {
  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node') && (is_numeric($path_args[2]))) {
    $variables['attributes']['class'][] = 'page-node-' . $path_args[2];
  }
}

/**
 * Implements hook_page_attachments().
 */
function custom_page_attachments(array &$attachments) {
  // Add custom.js to every page.
  $attachments['#attached']['library'][] = 'custom/custom';
}

/**
 * Implements hook_form_alter().
 */
function custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['#prefix'] = '<div class="members-login"><div class="block-title">Members login</div>';
    $form['#suffix'] = '<div class="first create-user"><a href="/join-member" title="Create a new member account.">Click here to find out how to join us</a><div class="forgot-user"><a href="/user/password">Forgot Password!</a></div></div></div>';
  }
  if ($form_id == 'webform_submission_ordinary_member_add_form') {
    
  }
  if ($form_id == 'webform_submission_resend') {
  }
}

/**
 * Implements custom_webform_element_alter().
 */
function custom_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
}


function custom_link_alter(&$variables) {
  if ($variables['text'] == 'Log in') {
    $variables['text'] = t('Members Login');
  }
}

/**
 * Implements custom_webform_element_alter().
 */
function custom_preprocess_webform_submission(&$variables) {
  $variables['sid'] = $variables['webform_submission']->get('sid')->getValue()[0]['value'];
}

function custom_preprocess_page(&$variables) {
  // Retrieve an array which contains the path pieces.
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);
  // (!empty($path_args) && $path_args[3] != 'edit') &&
  //
  $current_user = \Drupal::currentUser();
  $account = \Drupal\user\Entity\User::load($current_user->id());
  if ($path_args[1] == 'user' && $path_args[2] != 'login' && $path_args[2] != 'password' && $path_args[2] != 'logout') {
    $variables['current_page'] = 'user_profile';
    $variables['account_name'] = !empty($account->field_full_name->getValue()) ? $account->field_full_name->getValue()[0]['value'] : '';
    $variables['account_picture'] = (!empty($account->user_picture->entity)) ? ImageStyle::load('image_70x70')->buildUrl($account->user_picture->entity->getFileUri()) : '';
    $variables['account_email'] = (!empty($account->mail->getValue())) ? $account->mail->getValue()[0]['value'] : '';
  }
  else {
    $variables['current_page'] = '';
  }
}

/**
 * Implements hook_theme().
 */
function custom_theme($existing, $type, $theme, $path) {
  return array(
    'submission_pdf_invoice' => array(
      'variables' => array('items' => array(), 'title' => ''),
    ),
    'profile_user' => array(
      'variables' => array('items' => array(), 'title' => ''),
    ),
  );
}

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function custom_preprocess_entity_print(array &$variables) {
  $webform_submission = _webform_entity_print_preprocess_entity_print_get_webform_submission($variables['content']);
  if (!$webform_submission) {
    return;
  }
  
  
  $webform = $webform_submission->getWebform();
  // Add webform entity print CSS.
  /** @var \Drupal\webform\WebformThirdPartySettingsManagerInterface $third_party_settings_manager */
  $third_party_settings_manager = \Drupal::service('webform.third_party_settings_manager');
  // Append default print template CSS.
  $default_template = $third_party_settings_manager->getThirdPartySetting('webform_entity_print', 'template') ?: [];
  // kint($webform_submission);
  // kint($webform);
  // kint($default_template);
  
}

function custom_webform_submission_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $is_entity_print = in_array($route_name, ['entity_print.view.debug', 'entity_print.view']) || \Drupal::request()->request->get('_webform_entity_print');
  if ($is_entity_print) {
    // Add template header and footer.
    _webform_entity_print_webform_submission_template($build, $entity, $display);
  }
  elseif (in_array($display->getMode(), ['html', 'table'])) {
    // Add print links to HTML and Table mode.
    // kint( _webform_entity_print_webform_submission_links($build, $entity, $display));
    _webform_entity_print_webform_submission_links($build, $entity, $display);
  }
}

/**
 * Implements hook_preprocess_webform_submission_data().
 */
function custom_preprocess_webform_submission_data(array &$variables) {
  global $base_url;
  
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $webform_submission = $variables['webform_submission'] = $variables['elements']['#webform_submission'];
  
  //Get Data form webform print in templates
  $full_name_of_company = $webform_submission->getData()['full_name_of_company'];
  $company_registration_no = $webform_submission->getData()['company_registration_no'];
  $date_of_incorporation_of_company = date('d M Y', strtotime($webform_submission->getData()['date_of_incorporation_of_company']));
  $address = $webform_submission->getData()['address'];
  $name_designation = $webform_submission->getData()['name_designation'];
  $logo = $base_url . '' . file_url_transform_relative(file_create_url(theme_get_setting('logo.url')));
  
  $content_submission = array(
    'full_name_of_company' => $full_name_of_company,
    'company_registration_no' => $company_registration_no,
    'date_of_incorporation_of_company' => $date_of_incorporation_of_company,
    'address' => $address,
    'name_designation' => $name_designation,
    'logo' => $logo,
  );
  $template = [
    '#theme' => 'submission_pdf_invoice',
    '#title' => 'Demo1',
    '#items' => $content_submission,
  ];
  
  //Render form file twig templates => text/html
  $render_template = \Drupal::service('renderer')->render($template);
  print  $render_template;
  
  if ($variables['webform_submission'] instanceof WebformSubmissionInterface) {
    $variables['webform'] = $variables['webform_submission']->getWebform();
  }
}